<?php

/**
 * @file
 * Get and display something from the internet using a public API.
 */

/**
 * Implements hook_menu().
 */
function getthis_menu() {
  $items = array();
  $items['getthis/%getthis_plugin'] = array(
    'title' => 'Something from the internet',
    'page callback' => 'getthis_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_type().
 */
function getthis_ctools_plugin_type() {
  $plugins['Getthis\Service'] = array(
    'classes' => array('class'),
    'extension' => 'php',
    'cache' => TRUE,
  );
  return $plugins;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function getthis_ctools_plugin_directory($module, $type) {
  if ($module == 'getthis') {
    return 'lib/Drupal/getthis/Plugin/getthis/Service';
  }
}

/**
 * Loads a service plugin.
 */
function getthis_plugin_load($service) {
  ctools_include('plugins');
  return ctools_get_plugins('getthis', 'Getthis\Service', $service);
}
