<?php

/**
 * @file
 * Get and display something from the internet using a public API.
 */


/**
 * Implements hook_ctools_plugin_type().
 */
function getthis_ctools_plugin_type() {
  $plugins['Getthis\Service'] = array(
    'classes' => array('class'),
    'extension' => 'php',
    'cache' => TRUE,
  );
  return $plugins;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function getthis_ctools_plugin_directory($module, $type) {
  if ($module == 'getthis') {
    return 'lib/Drupal/getthis/Plugin/getthis/Service';
  }
}
